### ISSUE TITLE
nameframe-projectile and nameframe-perspective not on MELPA?

### ISSUE THREAD

**Issue by rkrug** [john2x/nameframe#4]
Hi
I just installed namespace from melpa but it seems that  nameframe-projectile and nameframe-perspective  are not on melpa.

Thanks,

Rainer

**Comment by john2x** [comment]
Hi, yes, sorry about that. There are some design issues at the moment on how nameframe-projectile and nameframe-perspective should be distributed. (See https://github.com/milkypostman/melpa/pull/3176 and https://github.com/milkypostman/melpa/pull/3177)

My bad for being too eager and stating in the readme that its up on MELPA. I'll update the readme.

For the mean time, can you use the manual install?

Thanks,
John

**Comment by rkrug** [comment]
John Louis Del Rosario notifications@github.com writes:

> Hi, yes, sorry about that. There are some design issues at the moment
> on how nameframe-projectile and nameframe-perspective should be
> distributed. (See https://github.com/milkypostman/melpa/pull/3176 and
> https://github.com/milkypostman/melpa/pull/3177)
> 
> My bad for being too eager and stating in the readme that its up on MELPA. I'll update the readme.
> 
> For the mean time, can you use the manual install?

Sure - I can do this.

Thanks,

Rainer

> Thanks,
> John
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/john2x/nameframe/issues/4#issuecomment-145735265

## 

Rainer M. Krug, PhD (Conservation Ecology, SUN), MSc (Conservation Biology, UCT), Dipl. Phys. (Germany)

Centre of Excellence for Invasion Biology
Stellenbosch University
South Africa

Tel :       +33 - (0)9 53 10 27 44
Cell:       +33 - (0)6 85 62 59 98
Fax :       +33 - (0)9 58 10 27 44

Fax (D):    +49 - (0)3 21 21 25 22 44

email:      Rainer@krugs.de

Skype:      RMkrug

PGP: 0x0F52F982

**Comment by CestDiego** [comment]
Please lets have it on MELPA :(  I find this is a great tool and what could be missing in the perfect setup for perspectives.

**Comment by rkrug** [comment]
Any news? I would really like to use this package from melpa.

**Comment by john2x** [comment]
At the moment I'm still waiting on MELPA maintainers to merge the PR's.

Maybe you can nudge them a bit? :smile:  milkypostman/melpa#3176 milkypostman/melpa#3177

**Comment by john2x** [comment]
Good news, everyone! Nameframe is now up on MELPA :smile: http://melpa.org/#/?q=nameframe

**Comment by rkrug** [comment]
John Louis Del Rosario notifications@github.com writes:

> Good news, everyone! Nameframe is now up on MELPA :smile: http://melpa.org/#/?q=nameframe

Great - thanks

Rainer

> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/john2x/nameframe/issues/4#issuecomment-148994354

## 

Rainer M. Krug, PhD (Conservation Ecology, SUN), MSc (Conservation Biology, UCT), Dipl. Phys. (Germany)

Centre of Excellence for Invasion Biology
Stellenbosch University
South Africa

Tel :       +33 - (0)9 53 10 27 44
Cell:       +33 - (0)6 85 62 59 98
Fax :       +33 - (0)9 58 10 27 44

Fax (D):    +49 - (0)3 21 21 25 22 44

email:      Rainer@krugs.de

Skype:      RMkrug

PGP: 0x0F52F982
