### ISSUE TITLE
Projectile + nameframe

### ISSUE THREAD

**Issue by ghost** [john2x/nameframe#5]
I've tried setting up name frame in different configurations (mostly using use-package). Right now I can see that in fact:

``` emacs-lisp
projectile-before-switch-project-hook's value is (nameframe-projectile--before-switch-project-hook)
```

but it does not seem to work. When switching projects using `projectile-switch-project` it continues to re-use the same frame, always. 

`name frame-create-frame` works and opens the currently active buffer in a new frame.

**Comment by john2x** [comment]
Hi. Can you verify what version of Projectile you are using? `projectile-before-switch-project-hook` is a recent (only few days) addition to Projectile. Thanks.

**Comment by ghost** [comment]
Seems to have been 
Projectile version: 20151011.527
Now at
Projectile version: 20151017.552

seems to work!
